{
 "title": "FoundationDB (exporter metrics)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kubernetes_cluster_name",
    "label": "kubernetes_cluster_name",
    "query": {
     "query": "label_values(fdb_client_status_available,cluster)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(fdb_client_status_available,env)"
    }
   },
   {
    "name": "fdb_cluster_name",
    "query": {
     "query": "label_values(fdb_client_status_available,fdb_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "fdb_client_status_available{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "fdb_client_status_healthy{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "Healthy"
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Backups running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "fdb_cluster_backup_tag_is_running{env=\"$env\", cluster=\"$kubernetes_cluster_name\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "{{backup_tag}}"
    }
   ]
  },
  {
   "title": "Backup tag restorable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "fdb_cluster_backup_tag_running_is_restorable{env=\"$env\", cluster=\"$kubernetes_cluster_name\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "{{backup_tag}}"
    }
   ]
  },
  {
   "title": "Backup RPO seconds behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "fdb_cluster_backup_tag_last_restorable_seconds_behind{env=\"$env\", cluster=\"$kubernetes_cluster_name\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "fdb_cluster_workload_operations_writes_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "writes_hz"
    },
    {
     "expr": "fdb_cluster_workload_operations_reads_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "reads_hz"
    },
    {
     "expr": "fdb_cluster_workload_transactions_committed_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "committed_hz"
    },
    {
     "expr": "fdb_cluster_workload_operations_location_requests_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "location_requests_hz"
    },
    {
     "expr": "fdb_cluster_workload_operations_low_priority_reads_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "low_priority_reads_hz"
    },
    {
     "expr": "fdb_cluster_workload_operations_read_requests_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "read_requests_hz"
    },
    {
     "expr": "fdb_cluster_workload_operations_memory_errors_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "memory_errors_hz"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fdb_cluster_workload_bytes_read_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "bytes_read_hz"
    },
    {
     "expr": "fdb_cluster_workload_bytes_written_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "bytes_written_hz"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "fdb_cluster_workload_keys_read_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "keys"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Cluster wide latency probe",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "fdb_cluster_latency_probe_commit_seconds{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "latency_probe_commit"
    },
    {
     "expr": "fdb_cluster_latency_probe_read_seconds{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "latency_probe_read"
    },
    {
     "expr": "fdb_cluster_latency_probe_transaction_start_seconds{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "latency_probe_transaction_start"
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Data set size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fdb_cluster_data_total_kv_size_bytes{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "total_kv_size_bytes"
    },
    {
     "expr": "fdb_cluster_data_total_disk_used_bytes{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "total_disk_used_bytes"
    }
   ]
  },
  { "title": "Data movement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Data movement",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fdb_cluster_data_moving_data_in_queue_bytes{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "in_queue_bytes"
    },
    {
     "expr": "fdb_cluster_data_moving_data_in_flight_bytes{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"}",
     "legendFormat": "in_flight_bytes"
    }
   ]
  },
  { "title": "All processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk IO reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk IO writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", storage=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", storage=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", storage=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", storage=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", storage=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", storage=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", log=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", log=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 140 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", log=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", log=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", log=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", log=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 130 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", master=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 141 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", master=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 141 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", master=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", master=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", master=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", master=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 131 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", coordinator=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 142 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", coordinator=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 142 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", coordinator=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", coordinator=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", coordinator=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", coordinator=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", commit_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", commit_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", commit_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{commit_proxy=\"1\", env=\"$env\", cluster=\"$kubernetes_cluster_name\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", commit_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", commit_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GRV proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 133 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", grv_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", grv_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", grv_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", grv_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", grv_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", grv_proxy=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 134 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", cluster_controller=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", cluster_controller=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", cluster_controller=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", cluster_controller=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", cluster_controller=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", cluster_controller=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Data distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", data_distributor=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", data_distributor=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 146 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", data_distributor=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", data_distributor=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", data_distributor=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", data_distributor=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Ratekeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 136 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", ratekeeper=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", ratekeeper=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 147 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", ratekeeper=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", ratekeeper=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", ratekeeper=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", ratekeeper=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resolver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 137 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_cpu_cores{cluster=\"$kubernetes_cluster_name\", resolver=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_reads_hz{cluster=\"$kubernetes_cluster_name\", resolver=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk IO writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 148 },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_writes_hz{cluster=\"$kubernetes_cluster_name\", resolver=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk free",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_disk_free{cluster=\"$kubernetes_cluster_name\", resolver=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_sent{cluster=\"$kubernetes_cluster_name\", resolver=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "avg by(fdb_pod_name) (fdb_cluster_processes_network_megabits_received{cluster=\"$kubernetes_cluster_name\", resolver=\"1\", env=\"$env\", fdb_cluster=\"$fdb_cluster_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}